import Head from "next/head.js"
import NavBar from "../components/NavBar.jsx"


export default function Home() {
  return (
    <div>
    <Head>
    <title>Solarzu</title>
    <meta name='description' content='Generated by create next app' />
    <link rel='icon' href='/favicon.ico' />
  </Head>
        <NavBar /> 
        {/*</>  */}
        {/* </> */}
    </div>
  )
}
