import Head from "next/head.js"

import HomePage from "../components/HomePage.jsx"
// import Checkout from "./Checkout.js"



export default function Home() {
  return (
    <div>
      <Head>
        <title>Solarzu</title>
        <meta name='description' content='Generated by create next app' />
        <link rel='icon' href='/favicon.ico' />
      </Head>
       <HomePage /> 
     
    </div>
  )
}




// "@truffle/hdwallet-provider": "^2.0.10-alpha.2",
 // "wyvern-schemas": "^0.6.15"